/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package code;

import org.junit.jupiter.api.Test;

import code.controller.ItemController;

import static org.junit.jupiter.api.Assertions.*;

class ItemControllerTest {
    
}
